### ISSUE TITLE
[Question] xstream dependency?

### ISSUE THREAD

**Issue by cordisvictor** [timothystone/blojsom#12]
Is XStream used by Blojsom, as XStream site reports?
[XStream](https://x-stream.github.io/references.html)

**Comment by timothystone** [comment]
A long time ago. You probably saw that in a quick search that this repository excludes it from couple of legacy packages. This repository only supports v3+ XStream was used as it is stated on the site in v2 as part of a migration tool.

**Comment by cordisvictor** [comment]
Yes, the github repo search revealed only the exclude. Thanks for the answer.
